### ISSUE TITLE
Roboto Fonts

### ISSUE THREAD

**Issue by mhartington** [delta98/ionic-material-design-lite#42]
Including the Roboto Font files isn't really necessary. The chromeview on android gives you access to the system font, similar to how iOS has `-apple-system-font`

Instead of included the various font files, you could simplify and use this instead

```css
  * {
    font-family: sans-serif;
  }
```

Then just use the various weights (100,200,300,500) where you need it.

Reference:
https://gist.github.com/dpogue/cf8561b0cfb9d40be95d#chrome-on-android

**Comment by delta98** [comment]
Thanks @mhartington

There's an option with the project to override default iOS styles in the config for those who want to use it across both platforms. iOS doesn't include the font as part of the platform. 

Do you have any suggestions as to how to include it in this scenario?

**Comment by mhartington** [comment]
You should still use the system font on iOS and not use Roboto. Even google apps on ios still use helvetica. What we're doing with an up-coming release of ionic is using the follow font-family property.

```
font-family: -apple-system, "Helvetica Neue", sans-serif;
```

**Comment by delta98** [comment]
OK, great. I'll update the typography and remove the fonts. I was worried about increasing the size of the project by including them, so thanks for the advice!

**Comment by mhartington** [comment]
Happy to help. Liking what I see so far. 

Mike Hartington

**Comment by obetomuniz** [comment]
Photos, Calendar and Chrome iOS still using Roboto Font at iOS. I really believe that the MD (including MDL) recommends this rule to our projects.

**Comment by delta98** [comment]
@obetomuniz do you have a reference to that? Might be worth taking a look at it further?

**Comment by obetomuniz** [comment]
@delta98 I can send prints from these Apps on my iPhone to our analysis, can be it? 

And about recommendation of MD. Here's the link: https://www.google.com/design/spec/style/typography.html

**Comment by delta98** [comment]
Yeah I've referenced the guidelines, @mhartington what do you think? I can't find anything that says to use system fonts on iOS over Roboto?

**Comment by mhartington** [comment]
Same here, no where in the guide lines does it say to use roboto on iOS. These are just guides and not rules, no need to follow them to a T if you ask me. My main concern when I opened the issue was overall files size. But if you're really concerned about making sure you see roboto on there, keep this in mind

![](http://qph.is.quoracdn.net/main-qimg-075917658168d375b3d176080e39988a?convert_to_webp=true)

The difference between Apples system font and Roboto are minimal. Just my 2¢.

**Comment by obetomuniz** [comment]
@mhartington @delta98 The print screens are here. I really want encourage us to use Roboto instead -apple-system Font, because if a day Apple resolve change your font, we'll need change it too without motive related with our pattern that is the MDL and the MDL use Roboto.

![image](https://cloud.githubusercontent.com/assets/1680157/8985435/cae4e040-36ad-11e5-9c93-e0765ed3cd18.png)
![image](https://cloud.githubusercontent.com/assets/1680157/8985444/d344bbde-36ad-11e5-92a6-2694187ac1fe.png)
![image](https://cloud.githubusercontent.com/assets/1680157/8985446/d8946738-36ad-11e5-9bd8-1f788bdf8f89.png)
![image](https://cloud.githubusercontent.com/assets/1680157/8985448/dd8042bc-36ad-11e5-810e-1bdce96b7504.png)
![image](https://cloud.githubusercontent.com/assets/1680157/8985449/e2b5b6e0-36ad-11e5-94e1-bc2e8587bb40.png)
![image](https://cloud.githubusercontent.com/assets/1680157/8985454/e9f9c9d2-36ad-11e5-80a2-4fa987dd6e3c.png)

**Comment by mhartington** [comment]
@obetomuniz same thing with android. If Google goes and changes roboto, you'll have an old out of date font. 

I'm not arguing if you should follow the guidelines to a T (I don't think you need to, and there are some bad things in there) but I'm making a point that people will notice file size before a font. 

The font files alone will increase the app size by 13MB. You can get something close to the same effect just using the built in options and not add another 13MB.

There are good reason why you should use this font declaration.

```
font-family: -apple-system, "Helvetica Neue", sans-serif;
```


1) only iOS will honor  -apple-system, "Helvetica Neue". Android will fail and fall and use san-serif (which will use the system roboto font)

2) iOS has their own design guidelines too that people should follow. IMO Material design does not belong in iOS (but thats just my opinion)

3) 13MB for a font is a hella lot. Why include it when you can get something close with no additional files. 

@delta98 Feel free to make what ever call you want. It's your project.

**Comment by delta98** [comment]
@mhartington I share the same concerns with file size, originally I hadn't included the fonts as part of the project because of the debt instantly imposed onto the developer without even starting to build out their application.

I have been looking at other options, including having an optional reference to the Google fonts service.

I'm going to have to weigh up the pros and cons, over the community expectations. Which is why I included it in the first place to be honest, as it was requested.

Thanks both for your opinions, I'll post an update once I've reached a decision.

**Comment by delta98** [comment]
I'm going to close this issue, as I've come to the conclusion that the best course of action is to remove the font files for the Roboto family except `woff` and `woff2` as they are supported by both iOS and Android.

Instead of 13MB this will reduce the font directory to a more acceptable ~1MB and as I agree with both @mhartington and @obetomuniz comments, I will provide developers with the option to include the fonts directly into their applications or choose to use the system fonts as this can be more performant and the MD guidelines are just that, guidelines. 

iOS should utilise it's own system font San Francisco and allow for changes in the future whilst also allowing developers to choose to use Roboto if they wish to stick closely to the guidelines on iOS and older versions of Android.
