### ISSUE TITLE
Some guidance of what will be included with RC1 and beyond

### ISSUE THREAD

**Issue by helmuthva** [delta98/ionic-material-design-lite#47]
Hi,

as a lot of developers would love to integrate Google Material Design with Ionic and the ionicmaterial.com project does not seem to be the way to go (not connected to original implementation of Google; seems to be dead - no commit's since months) i am currently reviewing your variant.

Can you please give me (and others) some guidance of what you aim to achieve with RC1 and beyond?

Esp.:
- RC1: Will it include all components of google material design light (cp. http://www.getmdl.io/components/index.html) or a subset - if it will be a subset, do you have an estimate which components will be included?
- Beyond: Do you aim to include some of the components of Angular Material (esp. FAB Speed Dial, Bottom Sheet, Toast) some time later or will you stick with what is provided by mdl upstream? // and yes i know, that you cannot directly use components of Angular Material as this would conflict with Ionic - the question is if you aim to port some of the interesting ones for ionic.

Regards and thx for the clarification

**Comment by delta98** [comment]
Hi @helmuthva thanks for the really interesting question. The aim for RC1 will be to implement all existing ionic components: Headers, Lists, Dialogs, Navigation, Buttons, Transitions etc. Essentially whatever you see within the Ionic documentation that has a UI will be presented using Material Design.

The aim of the project is primarily to provide a Material Design "look and feel" for Ionic, automatically when you use the Android platform. So there won't be any custom components are part of V1.

That being said, the greater objective will be to contribute back to MDL (I've implemented lists for Ionic, but these aren't available without MDL yet) and to also create custom components.

To answer your first question, it will be a subset and include only those currently used within Ionic, so that you can use the same directives on iOS and Android, but the latter will have the same "look and feel" as Material Design. This I feel is the most realistic expectation and will ensure a consistent and clear roadmap. 

Regarding beyond RC1 (V1) I will begin implementing additional components that are specific only to Material Design. Tool tips, toasts and bottom sheets as per your example will be part of this.

Once V1 is released I will define a clear roadmap and welcome RFCs from the community, more information about that will be made available in due time. 

I hope that's answered your questions.

**Comment by helmuthva** [comment]
Hi @delta98 thanks for the great response.

We will thus use your project in one of our projects - this is btw a smartphone _and_ tablet app - it would thus be great if you support http://ionicframework.com/docs/api/directive/exposeAsideWhen/ ;-)

Regarding V1 components - support for https://material.angularjs.org/latest/#/demo/material.components.fabSpeedDial would be great as this is a very powerful UX component for smartphone and tablet apps ,-)

Best Regards - looking forward to your RC1 - will provide back our results of using this and possibly some components later ,-)

**Comment by delta98** [comment]
Hi @helmuthva exposeAsAside will be released as part of RC1. Fab speed dialer may not be made a feature immediately.

If you are using it on a project, please be aware that there is a wiki that's updated as part of this repo, useful information is included there. 

But most importantly there might be some BC coming shortly as I prepare for release.

**Comment by JobaDiniz** [comment]
I want to start an ionic project using Material Design, however I'm a bit concern about the repositories I've found.
There is the [ionicmaterial](http://ionicmaterial.com/) which last release was May 20 (that's a long time). And there's this one, which is only 1 month old.

I saw that you @delta98 contributed in the [ionicmaterial](http://ionicmaterial.com/) repository. My question is:
Why did you create this repository instead of continuing helping [ionicmaterial](http://ionicmaterial.com/) to evolve?

**Comment by delta98** [comment]
@JobaDiniz I completely disagreed with the approach [ionicmaterial](ionicmaterial.com) has taken. It uses custom directives that make the Ionic upgrade path impossible to follow, the material design guidelines aren't followed correctly and in order to correct those issues you would have to start again. 

My contribution was very small, I believe it was a couple bug fixes and some assistance on issues, but unfortunately the way the collaborators handled the project and the community meant it was going to fail, you can see that in the way no one has actively responded or updated the project since May. No matter what contribution was made, there would be no way to get that project back on track, at least not in keeping with the original goals.

Over a month ago Google released [Material Design Lite](http://www.getmdl.io/), which provides a clear and concise set of components and sass files that can be used independently of an opinionated framework like Polymer or AngularJS. 

This was an exciting proposition that allowed for what I believe would be a better approach, whereby the Ionic directives were respected and extended only to add additional classes or actions only found within Material Design, allowing for a clean upgrade path for both MDL and Ionic. 

The approach is to ensure the application maintains the platform look and feel (iOS retains it's default styles) unless configured otherwise. So you can take a look at the demos within this project, replace `platform-android` with `platform-ios` and you'll see the components are presented as if they were on iOS. You couldn't do that with [ionicmaterial](ionicmaterial.com), it was either Material Design or nothing.

So to answer your question:
> Why did you create this repository instead of continuing helping ionicmaterial to evolve?

The original contributors are unresponsive to the community, the approach is completely different and this project utilises a library of JS and CSS that are provided directly by Google and the community to meet the MD guidelines. 

I've also ensured there are tangible deadlines, features and a roadmap to ensure a community can contribute and determine the future of the project based on the features and roadmap presented to them. 

I hope this has addressed your concerns, the project is still in development and RC1 is due for release on 31st Aug.

**Comment by JobaDiniz** [comment]
Thanks for clarifying.
